### ISSUE TITLE
ProArc 4.x.x PREMIS 2.2 nevalidní?

### ISSUE THREAD

**Issue by bezverec** [digitalizace/digivpraxi#5]
Po delší době jsme přešli z releasu ProArcu 3.8.2 na 4.0.3. Zatím nám vše prošlo bežnými procesy. Jediný zádrhel nastal při validaci Komplexním validátorem. Hází nám konzistentně ve všech balíčcích stejné ERRORy v technických metadatech v amd_mets_xxx.xml, například:

`Pravidlo PREMIS_VALID_BY_XSD: 108 problémů (108x ERROR)
Záznamy PREMIS v souborech SECONDARY-METS musí být validní podle XML Schema (premis_2.2.xsd).`
`ERROR: checkPremisIsValidByXsd: amd_mets_vkol-00apml_0007.xml: OBJ_001: UndeclaredPrefix: Cannot resolve 'premis:file' as a QName: the prefix 'premis' is not declared.`

Issue jsem našel jen 1 podobné.

https://github.com/NLCR/komplexni-validator/issues/98
https://github.com/NLCR/Standard_NDK/issues/98

Nedokážu z toho rozluštit, jestli se jedná o chybu ProArcu, Validátoru, nebo jen naší instance. Chtěl jsem zde proto zkušené metadataře a členy vývojových týmů poprosit o pomoc. Díky :)

**Comment by kerschfilip** [comment]
Zdravím,

V KNAV jsme narazili na stejnou chybu při validaci. Objevuje se v kombinaci s ProArcem [v4.0.3](https://github.com/proarc/proarc/releases/tag/v4.0.3) i novějšími verzemi a validátorem [v2.3](https://github.com/NLCR/komplexni-validator/releases/tag/v2.3).

Stejná chyba se ale objevila i když jsem zkusil validovat vzorovou monografii, kterou má NK vystavenou spolu s DMF, takže bych řekl, že to (snad) bude chyba validátoru.  Pohledem do XML se mi navíc zdá, že  prefix 'premis' deklarovaný je...

**Comment by bezverec** [comment]
@kerschfilip Díky za zpětnou vazbu, pomohlo nám to. Když jsem si je porovnával, metadata se v tomto oproti předchozím verzím zápisu ze starších verzí ProArcu liší, nebylo mi ale ani z pravidel jasné, jestli je to správně/špatně, nebo jestli to Validátor jen jako povolený zápis nezná. Validátor jsem, myslím, zkoušel 2.2.1 (Linux CLI) i 2.3 (Windows GUI) - starší i novější verzi DMF.
